### ISSUE TITLE
Disable the toast saying "The screen is pinned"

### ISSUE THREAD

**Issue by TobiasDuelli** [MewsSystems/mews-flutter#290]
Would be nice to have the possibility to disable the toast with the instruction on how to stop the kiosk mode.

**Comment by ookami-kb** [comment]
This is out of scope for the library, but you can easily do it by subscribing to the mode:

```dart
watchKioskMode().listen((mode) {
 if (mode == KioskMode.enabled) {
   // display toast
 }
});
```

**Comment by aososam** [comment]
@ookami-kb  I agree this would be a really useful feature.

I understand In order to avoid showing the message  "App is pinned" I have to:
1) Make my app the device owner (by running a line of code from the terminal)
2) WhiteList the app to use LockTask (devicePolicyManager.setLockTaskPackages)

However, to do the second one it seems that I need to create a Method channel but it could be added to this library.
I am following the example from this page:
https://medium.com/@vimalp015/making-your-android-device-to-be-a-kiosk-7ea3cba1b40c

**Comment by aososam** [comment]
Now I understand why it cannot be part of the package.
the app needs to have a custom DeviceAdminReceiver class.
👍🏻

**Comment by fabioselau077** [comment]
> Now I understand why it cannot be part of the package. the app needs to have a custom DeviceAdminReceiver class. 👍🏻

Did you find any solution for this?
