### ISSUE TITLE
How to close stream?

### ISSUE THREAD

**Issue by SyedAbdulBasit7** [MewsSystems/mews-flutter#527]

**Comment by ookami-kb** [comment]
Can you be more specific, please?

**Comment by SyedAbdulBasit7** [comment]
@ookami-kb Thank you for reply

I am currently working on a Flutter project and in quiz screen where I utilize a stream `_currentMode` initialized with `watchKioskMode()`. My goal is to ensure the proper disposal of this stream when the quiz screen is disposed, with the aim of avoiding any potential memory leaks or other related issues. Also I want to initialize it again when I open quiz screen again.

`late final Stream<KioskMode> _currentMode = watchKioskMode();
`

**Comment by alboiuvlad29** [comment]
@SyedAbdulBasit7  A `Stream` cannot be closed as it's just a shore of asynchronous data so there's nothing to "close", unless you begin to have clients listening to it. And because of that, the stream doesn't "begin" sending data until you listen to it.

In the example app provided, [here](https://github.com/MewsSystems/mews-flutter/blob/cbf5fa3623a7c4c8905cc1300676e799c71abc56/kiosk_mode/example/lib/main.dart#L57), the `StreamBuilder` subscribes and disposes the stream for you.

If you don't use `StreamBuilder`, then you have to manually dispose it.


```dart
class Foo extends StatefulWidget {
  const Foo({super.key});

  @override
  State<Foo> createState() => _FooState();
}

class _FooState extends State<Foo> {
  late final StreamSubscription<KioskMode> _subscription;

  @override
  void initState() {
    super.initState();
    _subscription = watchKioskMode().listen(_handleKioskModeSubscription);
  }

  void _handleKioskModeSubscription(KioskMode _) {
    // Handle the mode change
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ....
  }
}

```

**Comment by SyedAbdulBasit7** [comment]
I agreed
